version: 0.0
os: linux
files:
  - source: src
    destination: /var/www/my-nodejs-app
    exclude:
  - package-lock.json
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
      overwrite: true
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
